#!/bin/bash
#
# Kibana    Init script for Kibana
#
# chkconfig: 345 99 76
# processname: kibana
#
KIBANA_EXEC="/opt/kibana/bin/kibana"
LOG_FILE="/opt/kibana/kibana.log"
PID_FILE="/opt/kibana/kibana.pid"
RETVAL=0

case "$1" in
    "start" )
        if [ ! -f ${PID_FILE} ]; then
            echo "Starting Kibana..."
            $KIBANA_EXEC 1>"$LOG_FILE" 2>&1 &
            echo $! > "$PID_FILE"
            echo "Kibana started with pid $!"
        else
            echo "Kibana is Running."
        fi
    ;;
    "stop" )
        echo "Stopping Kibana..."
        kill `cat ${PID}`
        RETVAL=$?
        if test $RETVAL -eq 0 ; then
           rm -f ${PID}
        fi
    ;;
    *)
        echo "Usage: $0 {start | stop}"
        exit 0
    ;;
esac
exit $RETVAL
